version: "3.9"

services:
  taio_pwt:
    image: ghcr.io/ys00241/taiopwt2:latest
    container_name: taio_pwt
    ports:
      - "2004:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./csv_exports:/app/csv_exports
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
